### ISSUE TITLE
Connect to spo site with MFA

### ISSUE THREAD

**Issue by brasil1983** [potatoqualitee/SPReplicator#91]
Hello, is MFA supported?

**Comment by potatoqualitee** [comment]
no, but may be soon. i havent worked on this in a few years and plan to shortly.

**Comment by brasil1983** [comment]
Really hope so, absolutely great module! Still use it with on prem SP, unable with SPO because of MFA.
Regards :)

**Comment by potatoqualitee** [comment]
Thanks so much for the encouragement, @brasil1983. I've added support for MFA in the latest release. So happy you're enjoying the module!

**Comment by brasil1983** [comment]
This is Amazing, thx so much!
